version: '3.8'
services:
  flask-app:
    build: app/
    ports:
      - "80:5000"
    environment:
      - F_PORT=5000
      - DB_PASSWORD=test
      - DB_USER=test
    depends_on:
      - db
    networks:
      - flask-app-network
    
  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scientialab
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    networks:
      - flask-app-network

networks:
  flask-app-network:
    driver: bridge
  

