version: '3'

services:
  web:
    build: app/
    ports:
      - '80:80'
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '32000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
